# Generated by Django 3.0.5 on 2020-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('statuses_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('default_profile', models.BooleanField()),
                ('profile_use_default_background_image', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=160)),
            ],
        ),
    ]
