# Generated by Django 3.0.5 on 2020-08-14 17:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('account_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('statuses_count', models.IntegerField()),
                ('follower_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('default_profile', models.BooleanField()),
                ('profile_use_background_image', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=160)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2020, 8, 14, 17, 47, 13, 160885, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.FloatField()),
                ('search_time', models.DateTimeField(default=datetime.datetime(2020, 8, 14, 17, 47, 13, 195713, tzinfo=utc))),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect_bot.TwitterUser')),
            ],
        ),
    ]
