# Generated by Django 3.0.5 on 2020-08-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 1, 43, 806465)),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 1, 43, 843474)),
        ),
    ]
