# Generated by Django 3.0.5 on 2020-08-03 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detect_bot', '0002_auto_20200803_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 16, 5, 56, 281006, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 16, 5, 56, 244998, tzinfo=utc)),
        ),
    ]
